app:
  param1: 'param1'
  param2: 2
  list:
    - 'index1'
    - 'index2'
    - 'index3'
server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:9090/CompanyService?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: example
